name: ept jest CI

on:
  pull_request:
    paths:
      - "src/**"

jobs:
  jest:
    # プロセスが終了しない限り、デフォルトで job は6時間実行される。
    # そのため普段の平均実行時間を実行ログから調べ、最大値以上を設定値の目安にする
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.17.0]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: jest test
        run: |
          yarn
          yarn test

      # ガバレッジレポートを出力する
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn test:coverage
